name: "Install the dependencies for the HCI project"
description: "Install uv, and then use uv to install Python dependencies for the project"
runs:
  using: "composite"
  steps:
    - name: "Install uv"
      uses: "astral-sh/setup-uv@v5"
    - name: "Install Python dependencies"
      shell: bash
      run: "uv sync"
