# Generated by Django 5.2 on 2025-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField()),
                ('title', models.CharField()),
            ],
            options={
                'verbose_name': 'PubMed Article',
                'verbose_name_plural': 'PubMed Articles',
            },
        ),
    ]
