# Generated by Django 5.2 on 2025-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField(help_text='A PubMed ID is a unique numeric ID associated with the article.', verbose_name='PubMed ID')),
                ('title', models.CharField(verbose_name='Article Title')),
            ],
            options={
                'verbose_name': 'PubMed Article',
                'verbose_name_plural': 'PubMed Articles',
            },
        ),
    ]
