# Generated by Django 5.2 on 2025-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmedarticle',
            name='pubmed_id',
            field=models.CharField(verbose_name='PubMed ID'),
        ),
        migrations.AlterField(
            model_name='pubmedarticle',
            name='title',
            field=models.CharField(verbose_name='Article Title'),
        ),
    ]
