# Generated by Django 5.2 on 2025-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_pubmedarticle_pubmed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmedarticle',
            name='pubmed_id',
            field=models.CharField(help_text='A PubMed ID is a unique numeric ID associated with the article.', verbose_name='PubMed ID'),
        ),
    ]
