# Generated by Django 5.2 on 2025-05-01 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('affiliation_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Affiliation ID')),
                ('affiliation_name', models.CharField(max_length=255, verbose_name='Affiliation Name')),
            ],
            options={
                'verbose_name': 'Affiliation',
                'verbose_name_plural': 'Affiliations',
            },
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_affiliation', models.ForeignKey(blank=True, default='10119', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_curators', to='users.affiliation', verbose_name='Active Affiliation')),
                ('affiliations', models.ManyToManyField(to='users.affiliation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curator',
                'verbose_name_plural': 'Curators',
            },
        ),
    ]
