# Generated by Django 5.2 on 2025-04-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'verbose_name': 'Affiliation', 'verbose_name_plural': 'Affiliations'},
        ),
        migrations.AlterModelOptions(
            name='curator',
            options={'verbose_name': 'Curator', 'verbose_name_plural': 'Curators'},
        ),
    ]
