[tool.docformatter]
black = true
in-place = true
recursive = true
style = "sphinx"

[tool.isort]
profile = "black"

[tool.pylint.main]
# Files or directories to be skipped. They should be base names, not paths.
ignore = [".venv"]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings"