#!/usr/bin/env bash
#
# This script can be used to run most command line tasks for this project. You
# can create an alias for your shell:
#     alias run="./run"
# This script is inspired by https://github.com/adriancooney/Taskfile. This
# script assumes you're running it from the root of the repository.

# Exit immediately if a command returns a non-zero status.
set -o errexit

# The return value of a pipeline is the value of the last (rightmost) command to
# exit with a non-zero status, or zero if all commands in the pipeline exit
# successfully.
set -o pipefail

# The dev function runs the Django application in development mode.
function dev {
    cd example && python manage.py runserver
}

# Build the app for production deployment.
function build {
    cd example &&
        python manage.py collectstatic &&
        cd .. &&
        pip install -r requirements-lock.txt
}

# The prod function runs the Django application in production mode.
function prod {
    cd example && gunicorn --workers 2 example.wsgi
}

# Run the task the user supplies to the run script and time it.
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
