# Generated by Django 5.2 on 2025-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondo_id', models.CharField(help_text='The Mondo Disease Ontology ID, e.g., MONDO_0005052.', verbose_name='Mondo ID')),
                ('label', models.CharField(verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
    ]
