# Generated by Django 5.2 on 2025-04-28 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0002_alter_disease_mondo_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Disease",
            new_name="Mondo",
        ),
    ]
