name: "CI"
on:
  pull_request:
    branches:
      - "reorg"
  push:
    branches:
      - "reorg"
jobs:
  check_1_code_is_formatted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Make sure the code is properly formatted"
        run: "just qual-format-check"
  check_2_code_is_linted:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Make sure the code is free of lint errors"
        run: "just qual-lint"
  check_3_type_check_passes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run the type checker on the code"
        working-directory: ./src
        run: "just qual-type-check"
  check_4_django_check_passes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run the Django check utility"
        working-directory: ./src
        run: "just django-check"
  test_1_unit_tests_pass:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run unit tests"
        working-directory: ./src
        run: "just test-unit"
  test_2_component_tests_pass:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run component tests"
        working-directory: ./src
        run: "just test-component"
  test_3_integration_tests_pass:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run integration tests"
        working-directory: ./src
        run: "just test-integration"
  test_4_contract_tests_pass:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run contract tests"
        working-directory: ./src
        run: "just test-contract"
  test_5_e2e_tests_pass:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Run end-to-end tests"
        working-directory: ./src
        run: "just test-e2e"
  site_1_dev_docs_site_builds:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Build the developer documentation site"
        working-directory: ./docs
        run: "just docs-build-html"
  site_2_test_coverage_report_builds:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/install-python-dependencies"
      - uses: "./.github/actions/install-just"
      - name: "Collect test coverage stats"
        working-directory: ./src
        run: "uv run coverage run -m pytest"
      - name: "Build the test coverage report"
        working-directory: ./src
        run: "just coverage-build-html"
