# Generated by Django 5.2 on 2025-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(help_text='The HLA allele descriptor, e.g., A*01:01:01:119.', verbose_name='Descriptor')),
                ('car_id', models.CharField(help_text='A unique identifier for the HLA allele, e.g., CAHLA1449130330.', verbose_name='ClinGen Allele Registry ID')),
                ('car_url', models.URLField(verbose_name='ClinGen Allele Registry URL for the HLA Allele')),
            ],
            options={
                'verbose_name': 'HLA Allele',
                'verbose_name_plural': 'HLA Alleles',
            },
        ),
    ]
