# Generated by Django 5.2 on 2025-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allele',
            options={'verbose_name': 'Allele', 'verbose_name_plural': 'Alleles'},
        ),
        migrations.AlterField(
            model_name='allele',
            name='ipd_accession',
            field=models.CharField(verbose_name='IPD Accession'),
        ),
        migrations.AlterField(
            model_name='allele',
            name='name',
            field=models.CharField(verbose_name='IPD-IMGT Name'),
        ),
    ]
