# Generated by Django 5.2 on 2025-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1a_marker_type', models.CharField(choices=[('AL', 'Allele'), ('HA', 'Haplotype')], help_text='Is the study about an allele or a haplotype?', max_length=2, verbose_name='Marker Type')),
                ('step_1b_allele_resolution', models.CharField(choices=[('1F', '1-field'), ('2F', '2-field'), ('3F', '3-field'), ('GG', 'G-group'), ('PG', 'P-group'), ('4F', '4-field')], help_text='What is the allele resolution?', max_length=2, verbose_name='Allele Resolution')),
                ('step_1c_zygosity', models.CharField(choices=[('MO', 'Monoallelic (heterozygous)'), ('BI', 'Biallelic (homozygous)')], help_text='What is the zygosity?', max_length=2, verbose_name='Zygosity')),
                ('step_1d_phase_is_confirmed', models.BooleanField(help_text='Is the phase confirmed?', verbose_name='Phase is confirmed?')),
            ],
        ),
        migrations.CreateModel(
            name='Step2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_2_typing_method', models.CharField(choices=[('TSM', 'Tag SNPs or Microarrays'), ('SER', 'Serological'), ('IMP', 'Imputation'), ('LRT', 'Low-Resolution Typing'), ('HRT', 'High-Resolution Typing'), ('WES', 'Whole-Exome Sequencing'), ('SST', 'Sanger Sequencing-Based Typing'), ('WGS', 'Whole-Gene Sequencing'), ('NGS', 'Whole Genome Sequencing and/or Panel-Based NGS (>50x coverage)')], help_text='What method was used to determine the typing?', max_length=3, verbose_name='Typing Method')),
            ],
        ),
        migrations.CreateModel(
            name='Step3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gwas', models.BooleanField(help_text='Is this a GWAS result?', verbose_name='Is GWAS?')),
                ('significand', models.FloatField(help_text='The significand of the p-value.', verbose_name='Significand')),
                ('exponent', models.IntegerField(help_text='The exponent of the p-value.', verbose_name='Exponent')),
            ],
        ),
    ]
